App\Catalogue\Application\Command\CreateProductCommand:
    properties:
        name:
            -   NotBlank: ~
            -   Type: string

        price:
            -   NotNull: ~
            -   Type: integer
            -   GreaterThanOrEqual:
                    value: 0

        onHand:
            -   NotNull: ~
            -   Type: integer
            -   GreaterThanOrEqual:
                    value: 0
App\Catalogue\Application\Command\ReserveStockCommand:
    properties:
        items:
            -   Type: array
            -   NotBlank: ~
            -   All:
                    -   Collection:
                            allowExtraFields: false
                            allowMissingFields: false
                            fields:
                                product_id:
                                    -   NotBlank: ~
                                    -   Type: string
                                quantity:
                                    -   NotNull: ~
                                    -   Positive: ~
App\Catalogue\Application\Command\FulfillStockReservationCommand:
    properties:
        items:
            -   Type: array
            -   NotBlank: ~
            -   All:
                    -   Collection:
                            allowExtraFields: false
                            allowMissingFields: false
                            fields:
                                product_id:
                                    -   NotBlank: ~
                                    -   Type: string
                                quantity:
                                    -   NotNull: ~
                                    -   Positive: ~
