App\Catalogue\Application\Command\CreateProductCommand:
    properties:
        name:
            -   NotBlank: ~
            -   Type: string

        price:
            -   NotNull: ~
            -   Type: integer
            -   GreaterThanOrEqual:
                    value: 0

        onHand:
            -   NotNull: ~
            -   Type: integer
            -   GreaterThanOrEqual:
                    value: 0
App\Order\Application\Command\CreateOrderCommand:
    properties:
        amountToPay:
            -   Type: integer
            -   NotBlank: ~
            -   Positive: ~

        products:
            -   Type: array
            -   NotBlank: ~
            -   All:
                    -   Collection:
                            fields:
                                product_id:
                                    -   NotBlank: ~
                                    -   Type: string
                                name:
                                    -   NotBlank: ~
                                    -   Type: string
                                quantity:
                                    -   NotBlank: ~
                                    -   Type: numeric
                                    -   Positive: ~
                                price:
                                    -   NotBlank: ~
                                    -   Type: numeric
                                    -   Positive: ~
App\Catalogue\Application\Command\ReserveStockForOrderCommand:
    properties:
        orderId:
            -   Type: string
            -   NotBlank: ~
        items:
            -   Type: array
            -   NotBlank: ~
            -   All:
                    -   Collection:
                            allowExtraFields: false
                            allowMissingFields: false
                            fields:
                                product_id:
                                    -   NotBlank: ~
                                    -   Type: string
                                quantity:
                                    -   NotNull: ~
                                    -   Positive: ~
App\Catalogue\Application\Command\CommitReservedStockForOrderCommand:
    properties:
        orderId:
            -   Type: string
            -   NotBlank: ~
        items:
            -   Type: array
            -   NotBlank: ~
            -   All:
                    -   Collection:
                            allowExtraFields: false
                            allowMissingFields: false
                            fields:
                                product_id:
                                    -   NotBlank: ~
                                    -   Type: string
                                quantity:
                                    -   NotNull: ~
                                    -   Positive: ~
